include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    no_wildcard_variable_uses: true
    public_member_api_docs: false
    sort_pub_dependencies: false
    type_literal_in_constant_pattern: true
    valid_regexps: true
    void_checks: true
