name: target2sell_flutter
description: Flutter plugin for Target2Sell integration.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.1.2
  http: ^1.2.0
  logger: ^2.1.0
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:
